### ISSUE TITLE
Tidy the repo name.

### ISSUE THREAD

**Issue by RinChanNOWWW** [wjsvec/Make_BUPT_great_again-#2]
The name now doesn't look good. Let's change it to Make_BUPT_Great_Again.

**Comment by plazum** [comment]
附议

顺便借楼说一下，repo主（？不知道这种应该怎么叫）你把GitHub Pages开一下，这样访问你那些PDF更方便

**Comment by RinChanNOWWW** [comment]
> 附议
> 
> 顺便借楼说一下，repo主（？不知道这种应该怎么叫）你把GitHub Pages开一下，这样访问你那些PDF更方便

Owner.

**Comment by plazum** [comment]
> > 附议
> >
> > 顺便借楼说一下，repo主（？不知道这种应该怎么叫）你把GitHub Pages开一下，这样访问你那些PDF更方便
>
> Owner.

这个我知道，但是感觉看起来不像个称呼

**Comment by RinChanNOWWW** [comment]
LGTM
